### ISSUE TITLE
Can I add some Data Structure and algorithm programs in C. 

### ISSUE THREAD

**Issue by harshvardhan614** [Srishti44-g/HACTOBERFEST-2022-For-all-Begineers#34]

**Comment by Srishti44-g** [comment]
absolutely ... just create new folder for this then add your projects to it.

**Comment by harshvardhan614** [comment]
Hi @Srishti44-g , Thanks for assigning me this Issue.
I create a new DAta structure folder in which I add all my codes sequence and topic-wise.
PLs, merge my PR #118
