### ISSUE TITLE
Solve a problem in DSA

### ISSUE THREAD

**Issue by SongbidDey** [Srishti44-g/HACTOBERFEST-2022-For-all-Begineers#384]

**Comment by RayotiKar** [comment]
I want to take up the issue. Please assign me asap :).

**Comment by RayotiKar** [comment]
> _No description provided._

I want to take up the issue. Please assign me asap :).

**Comment by pritam1309** [comment]
please assign it to me i want to solve this issue ; )

**Comment by SamarS1ngh** [comment]
I would like to contribute to this issue, please allow me to do this.

**Comment by pritam1309** [comment]
Plz merge my pull request. ;)
