### ISSUE TITLE
Docy Trans a web app which translate file to any global language want to add

### ISSUE THREAD

**Issue by shivambmishra10** [Srishti44-g/HACTOBERFEST-2022-For-all-Begineers#478]
### About me:
**I am shivam mishra pre-final student and an open-source contributor**

### Issue:
**Docy trans a web app with 100% responsiveness, which convert any document file to any language gloablly.**

### Tech stack:
**HTML,CSS,EXPRESS JS, API's**

### Reference:
**I am attaching some ss of this web app for your reference.**
![5](https://user-images.githubusercontent.com/83920404/197330040-547e562b-2683-4cbe-8fdb-72593b0d7235.png)
![6](https://user-images.githubusercontent.com/83920404/197330042-2c6cbf3e-6b3c-41f8-8283-051132aeed93.png)

**Comment by Srishti44-g** [comment]
Awesome work ....keep it up!! :)

**Comment by Srishti44-g** [comment]
Yes you can add this
