### ISSUE TITLE
BMI Calculator

### ISSUE THREAD

**Issue by PushkarMishra15** [Srishti44-g/HACTOBERFEST-2022-For-all-Begineers#484]
I want to add a program for creating a BMI calculator in python

**Comment by PushkarMishra15** [comment]
Hey, I would be glad if you would assign me this task

**Comment by Zahid-khan786** [comment]
Hello sir, Can you assign me this issue, I create BMI Calculator in c++
This can be my first contribution on github

**Comment by ChandniJha630** [comment]
I can build a efficient BMI in python. Please Assign this issue to me

**Comment by Brainskull24** [comment]
Can You please assign this issue to me ?
@Srishti44-g
